# This is a basic workflow to help you get started with Actions

name: Workflow de démonstration

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - dev

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Nom du job
  hello:
    name: Hello World

    # Environnement virtuel du job
    # https://docs.github.com/articles/virtual-environments-for-github-actions
    runs-on: ubuntu-latest

    steps:
      - run: echo "HelloWorld From main"

